version: '3.8'
services:
  bot:
    container_name: 'Hikage'
    restart: unless-stopped
    volumes:
      - $PWD/resources:/home/bun/app/resources
    build:
      context: .
      dockerfile: Dockerfile
